//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simorgh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public Hotel()
        {
            this.ImageFile = new HashSet<ImageFile>();
            this.RoomType = new HashSet<RoomType>();
            this.Rating = new HashSet<Rating>();
        }
    
        public int HotelId { get; set; }
        public string HotelName { get; set; }
        public string Address { get; set; }
        public long Longtitude { get; set; }
        public long Latitude { get; set; }
        public string Description { get; set; }
        public byte Star { get; set; }
        public int CityId { get; set; }
    
        public virtual ICollection<ImageFile> ImageFile { get; set; }
        public virtual ICollection<RoomType> RoomType { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<Rating> Rating { get; set; }
    }
}
