//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simorgh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageFile
    {
        public int ImageFileId { get; set; }
        public string Path { get; set; }
        public Nullable<int> RoomTypeId { get; set; }
        public Nullable<int> HotelId { get; set; }
    
        public virtual Hotel Hotels { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
