//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simorgh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.ReplyToMessage = new HashSet<Message>();
        }
    
        public string MessageId { get; set; }
        public string FromUserId { get; set; }
        public string ToUserId { get; set; }
        public string MessageText { get; set; }
        public System.DateTime MessageTime { get; set; }
        public bool IsRead { get; set; }
        public string ReplyToMessageId { get; set; }
    
        public virtual AspNetUser FromUser { get; set; }
        public virtual AspNetUser ToUser { get; set; }
        public virtual Message Messages { get; set; }
        public virtual ICollection<Message> ReplyToMessage { get; set; }
    }
}
