//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simorgh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public string UserId { get; set; }
        public int HotelId { get; set; }
        public byte StaffBavior { get; set; }
        public byte RoomCleanliness { get; set; }
        public byte OutdoorCleanliness { get; set; }
        public byte Prestige { get; set; }
        public byte FoodQuality { get; set; }
        public byte EnvironmentQuality { get; set; }
        public byte PriceQualityRatio { get; set; }
        public byte Overal { get; set; }
    
        public virtual Hotel Hotels { get; set; }
        public virtual AspNetUser AspNetUsers { get; set; }
    }
}
