//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simorgh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationId { get; set; }
        public string UserId { get; set; }
        public int RoomTypeId { get; set; }
        public System.DateTime ReservationTime { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
        public Nullable<byte> AdultsCount { get; set; }
        public Nullable<byte> InfantsCount { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
