//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simorgh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomReview
    {
        public int RoomReviewId { get; set; }
        public string UserId { get; set; }
        public int RoomTypeId { get; set; }
        public System.DateTime ReviewTimestap { get; set; }
        public string Review { get; set; }
        public Nullable<int> UpVotes { get; set; }
        public Nullable<int> DownVotes { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
