// <auto-generated />
namespace Simorgh.Migrations.RoomTypeDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class changedkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedkey));
        
        string IMigrationMetadata.Id
        {
            get { return "201501020901567_changed key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
