// <auto-generated />
namespace Simorgh.Migrations.HotelDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class autogenkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(autogenkey));
        
        string IMigrationMetadata.Id
        {
            get { return "201501020838088_autogen key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
